# Generated by Django 5.2.4 on 2025-07-28 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='prodmast',
            fields=[
                ('prodid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('prodname', models.CharField(max_length=100)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='stckmain',
            fields=[
                ('stckid', models.AutoField(primary_key=True, serialize=False)),
                ('billdt', models.DateField()),
                ('totqty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='stckdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('prodid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.prodmast')),
                ('stckid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.stckmain')),
            ],
        ),
    ]
