# Generated by Django 5.2.4 on 2025-07-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stckmain',
            name='trntype',
            field=models.CharField(choices=[('IN', 'Inbound'), ('OUT', 'Outbound')], default='IN', max_length=3),
            preserve_default=False,
        ),
    ]
